# Generated by Django 4.0.3 on 2022-04-03 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=128, null=True, verbose_name='IP')),
                ('nodelocation', models.CharField(max_length=128, verbose_name='Node_Location')),
                ('trafficvar', models.CharField(max_length=128, verbose_name='Traffic_var')),
                ('toruse', models.CharField(max_length=128, verbose_name='Tor_Use')),
                ('nearnode', models.CharField(max_length=128, verbose_name='Near_Node')),
            ],
            options={
                'verbose_name': 'zeronet_packet',
                'verbose_name_plural': 'zeronet_packet',
                'db_table': 'capstone_board',
            },
        ),
    ]
