# Generated by Django 4.0.3 on 2022-04-25 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('localtime', models.CharField(max_length=128, null=True, verbose_name='local_time')),
                ('protoT', models.CharField(max_length=128, verbose_name='proto_T')),
                ('layerv', models.CharField(max_length=128, verbose_name='layer_V')),
                ('srcip', models.CharField(max_length=128, verbose_name='src_ip')),
                ('srcport', models.CharField(max_length=128, verbose_name='src_port')),
                ('dstip', models.CharField(max_length=128, null=True, verbose_name='dst_ip')),
                ('dstport', models.CharField(max_length=128, null=True, verbose_name='dst_port')),
                ('pktsize', models.CharField(max_length=128, null=True, verbose_name='pkt_size')),
            ],
            options={
                'verbose_name': 'zeronet_packet',
                'verbose_name_plural': 'zeronet_packet',
                'db_table': 'capstone_board',
            },
        ),
    ]
